name: Link check

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: astral-sh/setup-uv@6ee6290f1cbc4156c0bdd66691b2c144ef8df19a # v7
        with:
          enable-cache: true
      - run: uv sync
      - run: uv run mkdocs build
      - run: mkdir _lychee_root && ln -s ../site _lychee_root/mkdocs-zettelkasten
      - uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2
        with:
          args: --verbose --no-progress --root-dir _lychee_root ./site
          fail: true
